kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-web
spec:
  podSelector:
    matchLabels:
      access: accepted
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: web2
      ports:
        - port: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: 'busybox'
  namespace: default
  labels:
    access: accepted
spec:
  containers:
    - name: busybox
      image: 'busybox:1.31.1'
      command:
        ['/bin/sh', '-ec', 'while true; do echo "$(date)" ; sleep 1; done']
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
