apiVersion: v1
kind: Pod
metadata:
  name: 'pod2'
  namespace: cau2
  labels:
    app: 'pod2'
spec:
  containers:
    - name: c1
      image: 'busybox:1.31.1'
      command:
        [
          '/bin/sh',
          '-ec',
          'while true; do echo "$(date)" >> /vol/date.log; sleep 1; done',
        ]
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
      volumeMounts:
        - mountPath: /vol
          name: fileserver-claim
    - name: c2
      image: 'busybox:1.31.1'
      command: ['/bin/sh', '-ec', 'tail -f /vol/date.log;']
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
      volumeMounts:
        - mountPath: /vol/
          name: fileserver-claim
  volumes:
    - name: fileserver-claim
      persistentVolumeClaim:
        claimName: fileserver-claim
