apiVersion: v1
kind: Pod
metadata:
  name: 'web'
  labels:
    app: 'web'
spec:
  containers:
    - name: web
      image: 'nginx:latest'
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
      ports:
        - containerPort: 80
          name: http
  nodeSelector:
    node: master
