apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  namespace: default
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - name: webapp-svc
      protocol: TCP
      port: 80
      targetPort: 80
